name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: cxreiff/github_workflows/.github/workflows/rust_tests.yml@main
    with:
      crate_type: "bin"
      linux_dependencies: ""
