name: release

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
    secrets:
      DEDICATED_TOKEN:
        description: "Github token with repo permissions."
      CARGO_REGISTRY_TOKEN:
        description: Token to publish to crates.io."
        required: true
    inputs:
      linux_dependencies:
        description: "Linux libs to install before building."
        required: false
        default: ""
        type: string

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.DEDICATED_TOKEN }}

      - name: linux dependencies
        if: ${{ inputs.linux_dependencies != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends ${{ inputs.linux_dependencies }}

      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.DEDICATED_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
