name: release
# see https://release-plz.ieni.dev/docs/github
# for more information

permissions:
  pull-requests: write
  contents: write

on:
  workflow_call:
    secrets:
      CARGO_REGISTRY_TOKEN:
        description: "token to publish to crates.io"
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: linux deps
        run: sudo apt install libasound2-dev libudev-dev
      - name: install rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
